---
pve_lxc_lifecycle_action: create
pve_lxc_lifecycle_start_after_create: true

# Resource defaults — override per host in host_vars
pve_lxc_lifecycle_memory: 512
pve_lxc_lifecycle_cores: 1
pve_lxc_lifecycle_rootfs: "local-lvm:8"
pve_lxc_lifecycle_template: ""
