all:
  children:
    pve_all:
      children:
        pve_vms:
          hosts:
            example-vm:
              ansible_host: 192.0.2.10

        pve_lxc:
          hosts:
            example-lxc:
              ansible_host: 192.0.2.20