---
- name: Skip snapshot if disabled
  ansible.builtin.debug:
    msg: "Snapshots disabled"
  when: not snapshot_enabled
  tags: snapshot

- name: Snapshot virtual machines
  ansible.builtin.include_tasks: vm.yml
  when:
    - snapshot_enabled
    - "'pve_vms' in group_names"
  tags: snapshot

- name: Snapshot LXC containers
  ansible.builtin.include_tasks: lxc.yml
  when:
    - snapshot_enabled
    - "'pve_lxc' in group_names"
  tags: snapshot