---
- name: Skip verification when disabled
  ansible.builtin.debug:
    msg: "Verification disabled"
  when: not verify_common_enabled
  tags: verify

- name: Run verification dispatcher
  ansible.builtin.include_tasks: dispatcher.yml
  when: verify_common_enabled
  tags: verify
