---
- name: Create virtual machine
  community.general.proxmox_kvm:
    api_host: "{{ pve_api_host }}"
    api_user: "{{ pve_api_user }}"
    api_token_id: "{{ pve_api_token_id }}"
    api_token_secret: "{{ pve_api_token_secret }}"
    node: "{{ pve_node }}"
    vmid: "{{ pve_vm_id }}"
    name: "{{ inventory_hostname }}"
    memory: "{{ pve_vm_lifecycle_memory }}"
    cores: "{{ pve_vm_lifecycle_cores }}"
    net:
      net0: "virtio,bridge={{ pve_vm_lifecycle_bridge }}"
    state: present
  delegate_to: localhost

- name: Start VM after creation
  ansible.builtin.include_tasks: start.yml
  when: pve_vm_lifecycle_start_after_create
