---
- name: Upgrade packages
  community.general.apk:
    upgrade: true
    update_cache: true

- name: Install security packages
  community.general.apk:
    name:
      - openssh
      - iptables
    state: present

- name: Configure SSH hardening
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: "PermitRootLogin {{ os_hardening_ssh_permit_root_login }}"
  notify: Restart ssh

- name: Disable SSH password authentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: "PasswordAuthentication {{ os_hardening_ssh_password_authentication | ternary('yes', 'no') }}"
  notify: Restart ssh
