---
- name: Ensure packages are up to date
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist

- name: Install security packages
  ansible.builtin.apt:
    name:
      - unattended-upgrades
      - apt-listchanges
      - ufw
    state: present

- name: Configure unattended upgrades
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";
  when: os_auto_updates_enabled

- name: Configure SSH hardening
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: "PermitRootLogin {{ ssh_permit_root_login }}"
  notify: restart ssh

- name: Disable SSH password authentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: "PasswordAuthentication {{ ssh_password_authentication | ternary('yes','no') }}"
  notify: restart ssh

- name: Enable UFW firewall
  community.general.ufw:
    state: enabled
    policy: deny
  when: os_firewall_enabled

- name: Allow SSH through firewall
  community.general.ufw:
    rule: allow
    name: OpenSSH
  when: os_firewall_enabled
