---
- name: Install services
  ansible.builtin.include_tasks: install.yml
  when: service_common_services | length > 0

- name: Manage services
  ansible.builtin.include_tasks: manage.yml
  when: service_common_services | length > 0
