---
- name: Enable and start services
  ansible.builtin.service:
    name: "{{ item.name }}"
    enabled: "{{ service_enable }}"
    state: "{{ service_state }}"
  loop: "{{ services }}"
  loop_control:
    label: "{{ item.name }}"