---
- name: Enable and start services
  ansible.builtin.service:
    name: "{{ item.name }}"
    enabled: "{{ service_common_enable }}"
    state: "{{ service_common_state }}"
  loop: "{{ service_common_services }}"
  loop_control:
    label: "{{ item.name }}"
