---
# Enable hardening
os_hardening_enabled: true

# SSH hardening
os_hardening_ssh_permit_root_login: "prohibit-password"
os_hardening_ssh_password_authentication: false

# Firewall
os_hardening_firewall_enabled: true

# Updates
os_hardening_auto_updates_enabled: true
