---
- name: Skip rollback when disabled
  ansible.builtin.debug:
    msg: "Automatic rollback disabled"
  when: not pve_rollback_auto
  tags: rollback

- name: Rollback virtual machines
  ansible.builtin.include_tasks: vm.yml
  when:
    - pve_rollback_auto
    - "'pve_vms' in group_names"
  tags: rollback

- name: Rollback LXC containers
  ansible.builtin.include_tasks: lxc.yml
  when:
    - pve_rollback_auto
    - "'pve_lxc' in group_names"
  tags: rollback
