---
- name: Update apk cache
  community.general.apk:
    update_cache: true
  when: os_base_update_packages

- name: Upgrade packages
  community.general.apk:
    upgrade: true
  when: os_base_update_packages

- name: Install common packages (Alpine)
  community.general.apk:
    name: "{{ os_base_common_packages + os_base_alpine_packages }}"
    state: present
